# Generated by Django 4.2.24 on 2025-09-14 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='guest_count',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(70)]),
        ),
    ]
