# Generated by Django 4.2.24 on 2025-09-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_bookingrequest_guest_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='description',
            field=models.TextField(blank=True, help_text='Event details (for open events)'),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='message',
            field=models.TextField(blank=True, help_text='Special requests, dietary restrictions, setup notes'),
        ),
    ]
