# Generated by Django 4.2.24 on 2025-12-13 08:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0004_bookingrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingRequest',
            new_name='Booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelTable(
            name='booking',
            table='booking_bookingrequest',
        ),
    ]
